spring.application.name=chs

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.enabled=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
springdoc.api-docs.enabled=true

jwt.secret=mysupersecretkeythatshouldbe32bytesmin448888
jwt.expiration=3600000
server.servlet.context-path=/api
