spring.application.name=chs
spring.datasource.url=jdbc:mysql://localhost:3306/book_database?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Nero0410
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
springdoc.api-docs.enabled=true

jwt.secret=mysupersecretkeythatshouldbe32bytesmin448888
jwt.expiration=3600000


